### ISSUE TITLE
Have you verified that the GPS location recording function is good on different phones?

### ISSUE THREAD

**Issue by Jia-le-wang** [tszheichoi/awesome-sensor-logger#1]
Sensor Logger is the best APP I've seen since GetSensorData. However, I couldn't get a GPS track in my tests on the Mi 8, Huawei P40, Samsung S20 and many other phones. I switched to a different Sensor Logger version, but all the phones still had empty GPS files. I suspect this is a common problem, isn't it? I made sure all the phones had location privileges turned on. Have you verified that the GPS location recording function is good on different phones?

**Comment by tszheichoi** [comment]
Upgrading version 1.10.3 should resolve this.
