### ISSUE TITLE
Iphone accelerometer coordinate frame

### ISSUE THREAD

**Issue by saltrack** [tszheichoi/awesome-sensor-logger#2]
The sensor logger app works perfectly on an android, however on the iphone app the coordinate frame for accelerometer and gyroscope reading seems to be different.  On an Iphone, I see that az is -9.8m/s^2 when the iphone is placed on a horizontal platform with the face up, while the android in the same orientation shows +9.8m/s^2. 

What frame of reference does the iphone accelerometer use ?

**Comment by tszheichoi** [comment]
Please refer to the diagram on this support page https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events
