### ISSUE TITLE
Gyro data from headphones

### ISSUE THREAD

**Issue by gershhub** [tszheichoi/awesome-sensor-logger#26]
I've noticed that headphone data does not include the onboard gyroscope (rotation rate). Why is that? Is there any way that the gyroscope signal could be added to the logger?

**Comment by tszheichoi** [comment]
I will investigate this and get back to you.

**Comment by tszheichoi** [comment]
Can confirm this will be available in version 1.30, to be released soon.

**Comment by tszheichoi** [comment]
Version 1.30 is now available. Do re-open this issue if you run into further issues.
