### ISSUE TITLE
Sensor harmonisation does not affect headphone data

### ISSUE THREAD

**Issue by gershhub** [tszheichoi/awesome-sensor-logger#27]
Unit and reference frame harmonisation does not seem to be applied to headphone IMU data when enabled for phone data.

**Comment by tszheichoi** [comment]
That is indeed the case. The harmonisation option is currently applied to phone sensors only -- not AirPods and, as a matter of fact, Apple watches too. However, I agree it should. I will update the harmonisation option in the next update so that it is more consistent across the board.

**Comment by tszheichoi** [comment]
Can now confirm that this will be available as part of version 1.30

**Comment by tszheichoi** [comment]
Version 1.30 is now available. Do re-open this issue if you run into further issues.
