### ISSUE TITLE
Feature Request: Allow to delete data in the cloud 

### ISSUE THREAD

**Issue by stcz** [tszheichoi/awesome-sensor-logger#28]
As sometimes data is not usable (not because of the app) it would be great, if the investigator cloud delete data from the cloud to free space. I would really appreciate this feature. It is also fine to make the feature to a Plus or Pro feature.

**Comment by tszheichoi** [comment]
This is now possible as of about a week ago. You should see a delete button next to each recording when browsing them as an investigator on the study's site. 

<img width="1057" alt="Screenshot 2024-03-06 at 21 22 51" src="https://github.com/tszheichoi/awesome-sensor-logger/assets/30114997/17325535-5b83-417e-af20-d8926a913648">

**Comment by stcz** [comment]
You are right, I investigated that about two weeks ago. Thanks for the great Maintenance of the App!
