### ISSUE TITLE
Feature Request: Keep awake with proximity sensor to save battery

### ISSUE THREAD

**Issue by stcz** [tszheichoi/awesome-sensor-logger#29]
As we all know, it is difficult for many smartphone vendors to let tasks run in background the recordings typically have to run in Keep Awake mode.

A suggestion (from [here](https://github.com/phyphox/phyphox-android)) it would be great to have the possibility to lock the phone and turn the screen off, when the proximity sensor is triggered (as during a phone call). So it would be possible to keep the app awake, with display off, and put the phone into your pocket without randomly touching on the screen. 

I would be very happy to see this feature and I think this will be a real improvement for the app.

**Comment by tszheichoi** [comment]
Very interesting, thanks for bringing this to my attention. Seems possible, but I have to play around with it more to better understand how this will interact with various Sensor Logger functionalities. Will keep this thread updated once I have investigated a bit more.

**Comment by tszheichoi** [comment]
I can now confirm that this option will be available in version 1.30.

**Comment by stcz** [comment]
Thanks, that will be great :heart:

**Comment by tszheichoi** [comment]
Version 1.30 is now available. Do re-open this issue if you run into further issues.
