### ISSUE TITLE
Headphone sample rate

### ISSUE THREAD

**Issue by gershhub** [tszheichoi/awesome-sensor-logger#33]
I've observed a 25Hz sample rate from Airpods Pro 2 and Airpods Max. Comments on StackOverflow suggest that this is the going rate for Airpods (vs ~100Hz for the phone's inertial sensors). Docs from Apple are not very clear on this. Have you been able to get 100Hz from headphones? Either way would be good to update documentation to reflect that the headphones fs may be different.

**Comment by tszheichoi** [comment]
It is not configurable (and in fact variable). My experimentation is 25Hz on AirPods Pro 2 and 15Hz on older models. I will update the in-app description to include this information.
