### ISSUE TITLE
question about local coordinate systems alignment of iPhone, Airpods, and iwatch

### ISSUE THREAD

**Issue by LannnSun** [tszheichoi/awesome-sensor-logger#38]
Thank you very much for your excellent work. I want to ask, have the local coordinate systems of iPhone, Airpods, and iwatch been aligned? If not, how can I align them?

**Comment by tszheichoi** [comment]
They are aligned. You can check what the coordinate systems are for these devices here: https://github.com/tszheichoi/awesome-sensor-logger/blob/main/COORDINATES.md

**Comment by LannnSun** [comment]
thank you very much！

Kelvin Choi ***@***.***> 于2024年5月13日周一 22:10写道：
