### ISSUE TITLE
Request on citation requirement

### ISSUE THREAD

**Issue by Thorkee** [tszheichoi/awesome-sensor-logger#39]
Yo this sensor logger has been really awesome! I am publishing papers that part of the data is collected through this platform that I think it would be nice for me to cite this repo. Should I just cite this repo like what is normally done or should I cite any related paper?

Thanks

**Comment by tszheichoi** [comment]
Thanks for using Sensor Logger for your research. You can cite the repo and/or myself (https://orcid.org/0000-0002-5796-5263)

**Comment by Thorkee** [comment]
I am planning to cite it as
[X]	K. T. H. Choi, “tszheichoi / awesome-sensor-logger,” _GitHub_. https://github.com/tszheichoi/awesome-sensor-logger/.
