### ISSUE TITLE
Questions about quaternions recorded by headphones and watches

### ISSUE THREAD

**Issue by LannnSun** [tszheichoi/awesome-sensor-logger#41]
Thank you very much for your excellent work. I have a question about quaternions. The local coordinate system of the iPhone is set according to the phone screen. When I open Standardize Units & Frames, the local coordinate systems of the phone, watch, and headphone are aligned.  Are they aligned to  the local coordinate system of the mobile phone? Does it mean that the acceleration and angular velocity output of the watch and earphones are expressed in the local coordinate system of the mobile phone? What do the quaternions of watches and headphones represent?Looking forward to your reply, thank you very much!

**Comment by tszheichoi** [comment]
Closing this now, let me know if you run into further issues.
