### ISSUE TITLE
why you pretend as open in github? you are tricking users.

### ISSUE THREAD

**Issue by kunthar** [tszheichoi/awesome-sensor-logger#43]
You have your own domain. Any information provided here as .MD files can be there. No need pretend as you are openly sharing the information. Personally I do not decide to download and install this trickery app.

**Comment by tszheichoi** [comment]
The intention of this repository is to create a space where the community can collect and share useful tools, resources, and links to use alongside Sensor Logger. It allows for collaboration and PRs, so anyone can contribute new additions or improvements.

**Comment by kunthar** [comment]
I believe you should read the definition of the community again. But of course this is your show.
