### ISSUE TITLE
Is it possible to get the camera's metadata used for a particular collection? 

### ISSUE THREAD

**Issue by FRopero** [tszheichoi/awesome-sensor-logger#48]
Hi,

**Problem**: After some collections using the camera among other sensors, I cannot find the camera's metadata used for the data collection.

**Question**: Is it possible to get these metadata from the camera? e.g., focal length or sensor size.

Thanks in advance!

**Comment by FRopero** [comment]
Perfect,
Thanks you for your quick reply.

**Comment by tszheichoi** [comment]
This is now released as part of 1.40. Give it a go and let me know whether it works for you.
