### ISSUE TITLE
Recording of human temperature from apple watch 8

### ISSUE THREAD

**Issue by Pavlmits** [tszheichoi/awesome-sensor-logger#7]
Apple Watch 8 provides the ability to track human temperature as it is mentioned [here](https://support.apple.com/en-us/HT213275#:~:text=Apple%20Watch%20Series%208%20and,bias%20from%20the%20outside%20environment.). Will something like this be introduced to the app?

**Comment by tszheichoi** [comment]
The Apple Watch 8 measures body temperature during sleep every 5 seconds (as noted on [the link](https://support.apple.com/en-us/HT213275#:~:text=Apple%20Watch%20Series%208%20and,bias%20from%20the%20outside%20environment) you provided). This means the sensor is unsuitable for Sensor Logger which needs a way to get real-time data on demand. If it becomes possible to fetch the temperature data in real time then I'd love to add it to Sensor Logger!
